"""ISO 639 language-code → human display-name table.

Used to render readable headings and meta descriptions on ``/lang/{lang}``
pages (proposal 100, Phase 1) — e.g. ``pt`` → "Portuguese", so the server-
rendered surface reads "Hive posts in Portuguese" instead of "Hive posts in pt".

The keys cover the fastText ``lid.176`` label set (the worker's primary
language detector, see ``project/worker/classify.py``) plus the ISO 639-1
two-letter codes that ``json_metadata`` languages add. ``lang`` is already
constrained to 2–3 lowercase chars upstream (``_LANG_RE`` in ``ui.py``), so a
plain dict lookup with an uppercase-code fallback is enough — no external
dependency, keeping this importable anywhere ``categories.py`` is.
"""

# Plain text only (the caller HTML-escapes). Names are the common English
# exonyms; rare languages fall back to the uppercased code via the helper.
LANGUAGE_NAMES: dict[str, str] = {
    "af": "Afrikaans",
    "als": "Alemannic",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "arz": "Egyptian Arabic",
    "as": "Assamese",
    "ast": "Asturian",
    "av": "Avaric",
    "az": "Azerbaijani",
    "azb": "South Azerbaijani",
    "ba": "Bashkir",
    "bar": "Bavarian",
    "bcl": "Central Bikol",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bh": "Bihari",
    "bn": "Bengali",
    "bo": "Tibetan",
    "bpy": "Bishnupriya",
    "br": "Breton",
    "bs": "Bosnian",
    "bxr": "Russia Buriat",
    "ca": "Catalan",
    "cbk": "Chavacano",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "ckb": "Central Kurdish",
    "co": "Corsican",
    "cs": "Czech",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "diq": "Zazaki",
    "dsb": "Lower Sorbian",
    "dty": "Dotyali",
    "dv": "Dhivehi",
    "el": "Greek",
    "eml": "Emilian-Romagnol",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fr": "French",
    "frr": "Northern Frisian",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gd": "Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gom": "Goan Konkani",
    "gu": "Gujarati",
    "gv": "Manx",
    "he": "Hebrew",
    "hi": "Hindi",
    "hif": "Fiji Hindi",
    "hr": "Croatian",
    "hsb": "Upper Sorbian",
    "ht": "Haitian Creole",
    "hu": "Hungarian",
    "hy": "Armenian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "ie": "Interlingue",
    "ilo": "Iloko",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jbo": "Lojban",
    "jv": "Javanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "krc": "Karachay-Balkar",
    "ku": "Kurdish",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish",
    "lez": "Lezghian",
    "li": "Limburgish",
    "lmo": "Lombard",
    "lo": "Lao",
    "lrc": "Northern Luri",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mai": "Maithili",
    "mg": "Malagasy",
    "mhr": "Eastern Mari",
    "min": "Minangkabau",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "mrj": "Western Mari",
    "ms": "Malay",
    "mt": "Maltese",
    "mwl": "Mirandese",
    "my": "Burmese",
    "myv": "Erzya",
    "mzn": "Mazanderani",
    "nah": "Nahuatl",
    "nap": "Neapolitan",
    "nds": "Low German",
    "ne": "Nepali",
    "new": "Newari",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "oc": "Occitan",
    "or": "Odia",
    "os": "Ossetian",
    "pa": "Punjabi",
    "pam": "Pampanga",
    "pfl": "Palatine German",
    "pl": "Polish",
    "pms": "Piedmontese",
    "pnb": "Western Punjabi",
    "ps": "Pashto",
    "pt": "Portuguese",
    "qu": "Quechua",
    "rm": "Romansh",
    "ro": "Romanian",
    "ru": "Russian",
    "rue": "Rusyn",
    "sa": "Sanskrit",
    "sah": "Yakut",
    "sc": "Sardinian",
    "scn": "Sicilian",
    "sco": "Scots",
    "sd": "Sindhi",
    "sh": "Serbo-Croatian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tr": "Turkish",
    "tt": "Tatar",
    "tyv": "Tuvan",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vec": "Venetian",
    "vep": "Veps",
    "vi": "Vietnamese",
    "vls": "West Flemish",
    "vo": "Volapük",
    "wa": "Walloon",
    "war": "Waray",
    "wuu": "Wu Chinese",
    "xal": "Kalmyk",
    "xmf": "Mingrelian",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yue": "Cantonese",
    "zh": "Chinese",
}


def language_display_name(code: str) -> str:
    """Return the English display name for a language code, falling back to the
    uppercased code for entries not in the table (so a rare/unknown code still
    renders something legible rather than nothing)."""
    if not code:
        return ""
    return LANGUAGE_NAMES.get(code.lower(), code.upper())
